apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: konark111/backend
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: data-volume
          mountPath: "/app/tasks.db"
      volumes:
      - name: data-volume
        hostPath:
          path: /home/ubuntu/data/tasks.db



---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: NodePort  # Expose as NodePort service


